# This is a basic workflow to help you get started with Actions

name: Documentation

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gen_docs:
    name: JSDoc Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
        working-directory: ./source
      - run: npm run docs
        working-directory: ./source
      - uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'out'
          destination-github-username: cse110-sp21-group31
          destination-repository-name: cse110-sp21-group31-docs
          commit-message: 'Update generated documentation'
