# This is a basic workflow to help you get started with Actions

name: Node CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    name: ESLint Linting - Airbnb
    runs-on: ubuntu-latest\
    steps:
      - uses: actions/checkout@v2
      - run: npm run lint
        working-directory: ./source
  test:
    name: Jest Tests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run test
        working-directory: ./source
  gen_docs:
    name: JSDoc Documentation
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run docs
        working-directory: ./source
